[build]
builder = "nixpacks"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "backend"
buildCommand = "cd backend && npm install && npm run prisma:generate && npm run build"
startCommand = "cd backend && npm run prisma:deploy && npm run start"
healthcheckPath = "/api/health"
healthcheckTimeout = 30

[[services]]
name = "frontend"  
buildCommand = "cd frontend && npm install && npm run build"
startCommand = "cd frontend && npm run start"

[environments.production]
RAILWAY_DOCKERFILE_PATH = "Dockerfile"