version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: thesisai
      POSTGRES_PASSWORD: thesisai_password
      POSTGRES_DB: thesisai
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql://thesisai:thesisai_password@postgres:5432/thesisai"
      REDIS_URL: "redis://redis:6379"
      NODE_ENV: production
    depends_on:
      - postgres
      - redis
    ports:
      - "3001:3001"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_API_URL: "http://backend:3001/api"
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  postgres_data: